server:
  port: 8091

eureka:
  instance:
    #集群这个名字必须相同，如果没有填写，默认为unkown
    appname: eureka-peer
    hostname: eureka-peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-peer2:8092/eureka/
